FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase
    Mimic_Grab_Ball:
      id: 4
      type: Mimic
    Mimic_Single_Stand:
      id: 5
      type: Mimic


  Passive:
    transitions: 
      FixStand: LT + up.on_pressed
    mode: [
      1,1,1,1,1,1,
      1,1,1,1,1,1,
      1,1,1,
      1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,
    ]
    kd: [
      3,3,3,3,3,3,
      3,3,3,3,3,3,
      3,3,3,
      3,3,3,3,3,3,3,  
      3,3,3,3,3,3,3,  
    ]


  FixStand:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RT + A.on_pressed

    kp: [
      100,100,100,150,40,40,
      100,100,100,150,40,40,
      200,200,200,
      40,40,40,40,40,40,40,
      40,40,40,40,40,40,40,
    ]
    kd: [
      2,2,2,4,2,2,
      2,2,2,4,2,2,
      5,5,5,
      10,10,10,10,10,10,10,
      10,10,10,10,10,10,10,
    ]
    ts: [0, 2]
    qs: [
      [],
      [ -0.1, 0,0,0.3,-0.2,0,
        -0.1, 0,0,0.3,-0.2,0,
        0,0,0,
        0.35, 0.18,0,0.87,0,0,0,
        0.35,-0.18,0,0.87,0,0,0
      ]
    ]


  Velocity:
    transitions: 
      Passive: LT + B.on_pressed
      Mimic_Grab_Ball: RB + X.on_pressed
      Mimic_Single_Stand: RB + Y.on_pressed

    policy_dir: config/policy/velocity


  Mimic_Grab_Ball:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RT + A.on_pressed
      Mimic_Single_Stand: RB + Y.on_pressed

    motion_file: config/policy/mimic/grab_ball/params/grabBallWithSingleHandRefAction.npz
    policy_dir: config/policy/mimic/grab_ball/
    need_set_kpkd: true
    time_start: 0.0
    time_end: 1000.0


  Mimic_Single_Stand:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RT + A.on_pressed
      Mimic_Grab_Ball: RB + X.on_pressed

    motion_file: config/policy/mimic/single_stand/params/single_stand_with_centermodify.npz
    policy_dir: config/policy/mimic/single_stand/
    need_set_kpkd: false
    time_start: 0.0
    time_end: 1000.0